### PR TITLE
load joints information using SDF information.

### PR DESCRIPTION
**Pull request by gustavoneves12**
load joints information from SDF file

### CODE REVIEW

**Comment by doudou** [comment]
You forgot to add the dependency on sdformat in the manifest.xml, as well as a PR to include simulation/sdformat in http://github.com/rock-core/rock-package_set

**Comment by gustavoneves12** [comment]
Maybe, the best place is control/sdformat. What do you think?

**Comment by doudou** [comment]
I think you're right. That's best given that urdfdom is already there.

**Comment by gustavoneves12** [comment]
I need to modify the http://github.com/rock-core/rock-package_set?
So, I will create a fork and made a PR?

**Comment by doudou** [comment]
> So, I will create a fork and made a PR?

Yes, and I will add some more stuff in that PR ... It's about time we start pushing some code in Rock

**Comment by maltewi** [comment]
Can't merge before https://github.com/rock-core/rock-package_set/pull/49 got merged

**Comment by doudou** [comment]
I'm closing this. Let's reopen when we're done with (read: well tested) the SDF integration on the BIR side

**Pull request closed without merging**
