### PR TITLE
src: fix to update to base-logging and new shared_ptr in urdf

### PR DESCRIPTION
**Pull request by jhidalgocarrio**

### CODE REVIEW

**Comment by maltewi** [comment]
Thanks for the PR. Could you please have a look at the changes I added to your rock-gui/gui-robot_model#11 (via rock-gui/gui-robot_model@b3e1e89) and apply them also here?

**Comment by jhidalgocarrio** [comment]
Alright. It is updated. I also include base/logging in the manifest for autoproj in this repo.
I missed the manifest update in [rock-gui/gui-robot_mode](https://github.com/rock-gui/gui-robot_model/blob/master/manifest.xml) (could you please add it)

**Comment by jmachowinski** [comment]
Please use the URDF typedef instead of std::sharedPtr

**Comment by jhidalgocarrio** [comment]
I saw it for [urdf::ModelInterfaceSharedPtr](https://github.com/ros/urdfdom_headers/blob/5cb0b6b6a99eeeff5cd111dabd0093a29305a2f9/urdf_world/include/urdf_world/types.h#L48) but I did not find it for urdf::Joint

**Comment by jmachowinski** [comment]
They are provided through a macro :
#define URDF_TYPEDEF_CLASS_POINTER(Class) \
class Class; \
typedef boost::shared_ptr<Class> Class##SharedPtr; \
URDF_TYPEDEF_CLASS_POINTER(Joint);

So JointSharedPtr should exist.

**Comment by jhidalgocarrio** [comment]
Alright, thanks a lot. I included urdf::JointSharedPtr for urdf::Joint

**Pull request merged**
